# Sphinx configuration for the CPP-MDANCE documentation.
#
# Build with:
#     .venv/bin/sphinx-build -b html docs docs/_build/html
#
# The prose sources are Markdown, so myst-parser does the parsing; there is no
# reStructuredText in this tree.

project = "CPP-MDANCE"
author = "MDANCE contributors"
copyright = "2026, MDANCE contributors"

extensions = [
    "myst_parser",
]

# Markdown only -- keep .rst registered so an autogenerated stub would still
# build if one is ever added.
source_suffix = {
    ".md": "markdown",
    ".rst": "restructuredtext",
}

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# GitHub-compatible anchors for headings up to <h3>, so in-page links behave the
# same here as they do when the same files are viewed on GitHub.
myst_heading_anchors = 3

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "smartquotes",
    "substitution",
]

html_theme = "furo"
html_title = "CPP-MDANCE"
html_static_path = []

# Warn about broken cross-references.
nitpicky = False
